api_platform:
  title: "API d'accès aux données tarifaires Tempo EDF"
  description: "Cette API donne un accès facile aux codes couleurs tarifaires de l'offre d'électricité Tempo en France, commercialisée par EDF (tarif réglementé, option Tempo). L'API fournit le code couleur du jour et du lendemain, ainsi que l'historique des couleurs depuis 2020."
  version: "1.0.0"
  show_webby: false

  openapi:
    contact:
      name: Jean-Baptiste Romain
      #url:
      email: jbromain25@gmail.com

  formats:
    json:
      mime_types: ["application/json"]

    jsonld:
      mime_types: ["application/ld+json"]

    html:
      mime_types: ["text/html"]
